spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: false

server:
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3,TLSv1.2
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_AES_128_CCM_SHA256
    key-store: ${SERVER_SSL_KEYSTORE}
    key-store-password: ${SERVER_SSL_KEYSTOREPASSWORD}
dgc:
  userAgentLogging:
    interval: ${CWA_USERAGENTLOGGING_INTERVAL:false}
    encryptionPublicKey: ${CWA_USERAGENTLOGGING_ENCRYPTIONPUBLICKEY:}
    cleanupInterval: ${CWA_USERAGENTLOGGING_CLEANUPINTERVAL:86400}
    maxAge: ${CWA_USERAGENTLOGGING_MAXAGE:7}
