server:
  port: 8080
spring:
  application:
    name: dgca-businessrule-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
    database-change-log-table: BR_CHANGELOG
    database-change-log-lock-table: BR_CHANGELOG_LOCK
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  server:
    ssl:
      enabled: false
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  health:
    probes:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
dgc:
  businessRulesDownload:
    timeInterval: 1800000
    lockLimit: 3600000
  valueSetsDownload:
    timeInterval: 1800000
    lockLimit: 3600000
  countryListDownload:
    timeInterval: 1800000
    lockLimit: 3600000
  allowedCorsUrls: ${DGC_CORS_ENABLED_URL}
  gateway:
    connector:
      enabled: true
      endpoint: ${DGC_GATEWAY_CONNECTOR_ENDPOINT}
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store:
        password: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH}
      tls-key-store:
        alias: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH:false}
      trust-anchor:
        alias: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PATH}


